### PR TITLE
Fix Netlify deployment with a no-op build script

### LINKED ISSUE #159: Static template fails to deploy to Netlify due lack of `build` command
Steps to reproduce:
1. Create new sandbox using "Static" template
2. Deploy to Netlify from CodeSandbox left sidebar
3. Wait until build kicks off
4. Click "View logs" (after it appears under the Deploy button)

Expected: Site deploys to Netlify
Actual: `npm ERR! missing script: build`

Reproduction: https://codesandbox.io/s/silly-https-4isim

### PR DESCRIPTION
**Pull request by jevakallio**
Fixes #159

### CODE REVIEW

**Comment by CompuIves** [comment]
Thank you!!

**Comment by pablopunk** [comment]
Just FYI, when I create a sandbox from this template and try to deploy an `api/index.js` to Vercel, it breaks. It's solved by removing that `"build"` script.

**Comment by SaraVieira** [comment]
Oh god, because removing it breaks netlify 😭

**Comment by pablopunk** [comment]
@SaraVieira we could open an issue on Vercel's platform, because having a `build` script makes Vercel look for a `public/` folder

**Comment by SaraVieira** [comment]
Honestly I don't think this is anyone's bug 

It's just a fact 😂

I am gonna need yo modify the package.json it it's a static template

**Comment by pablopunk** [comment]
@SaraVieira sure, I have no problem doing that. I just wanted to let you guys know and leave the solution here in case anyone runs into this error in the future.

**Comment by SaraVieira** [comment]
Oh sorry, I meant I am going to need to modify the package.json, that sounded like I was just telling you to do it

Sorry, it's because I am on the phone  

I'll do a PR for that tomorrow, thank you for letting us know

**Comment by pablopunk** [comment]
haha no problem... I'm guessing you mean modifying the scripts (I guess [here](https://github.com/codesandbox/codesandbox-client/blob/0fc773972a657a32c3c9c013b2b9475e3fc321d2/packages/common/src/templates/template.ts#L211)) before a deployment right?

**Pull request merged**
